# This file is machine-generated - editing it directly is not advised

julia_version = "1.13.0"
manifest_format = "2.1"
project_hash = "ef9723eeb744d88e7ae9dc0c5759886fda705436"

[[deps.OrderedCollections]]
git-tree-sha1 = "d321bf2de576bf25ec4d3e4360faca399afca282"
registries = "General"
uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
version = "1.6.0"

[[deps.Reexport]]
git-tree-sha1 = "57d8440b0c7d98fc4f889e478e80f268d534c9d5"
registries = "General"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "1.0.0"

[[deps.SecurityPackage]]
deps = ["OrderedCollections", "Reexport"]
path = "."
uuid = "88888888-8888-8888-8888-888888888888"
version = "0.1.0"

[registries.General]
url = "https://github.com/JuliaRegistries/General.git"
uuid = "23338594-aafe-5451-b93e-139f81909106"
